-- AlterEnum
ALTER TYPE "PackageStatus" ADD VALUE 'READY_FOR_PICKUP' AFTER 'RECEIVED';
ALTER TYPE "PackageStatus" ADD VALUE 'OUT_FOR_DELIVERY' AFTER 'SHIPPED';
ALTER TYPE "PackageStatus" ADD VALUE 'DELIVERED' AFTER 'OUT_FOR_DELIVERY';

-- AlterTable
ALTER TABLE "packages" ADD COLUMN "rate" DOUBLE PRECISION;
ALTER TABLE "packages" ADD COLUMN "cost" DOUBLE PRECISION;
