-- No-op migration. admin's schema.prisma is catching up to columns/tables
-- that already exist in the live database — added over time by
-- customer-portal's own hand-applied migrations, back when that app
-- managed its own tables directly (portal_users, portal_settings,
-- delivery_assignments, shipping_rates, locations, faq_items, manifests,
-- authorized_pickup_people). `prisma migrate diff` against the live
-- database confirms zero drift: this migration exists only so admin's own
-- tracked history (_prisma_migrations) reflects that admin now owns the
-- full schema, as part of retiring customer-portal's direct DB access in
-- favor of an internal API + SDK (see packages/admin-sdk).
